on:
  push:
    paths:
      - .github/workflows/build_docs.yml
      - docs/**
  pull_request:
    paths:
      - .github/workflows/build_docs.yml
      - docs/**
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p site/api/

      - uses: asyncapi/github-action-for-cli@v3.1.2
        with:
          command: generate
          filepath: docs/api/asyncapi.yaml
          template: '@asyncapi/html-template@2.1.7'
          output: site/api/

      - run: |
          tar -cvf artifact.tar -C site/ .

      - uses: actions/upload-artifact@v4
        with:
          name: api-pages
          path: |
            artifact.tar


  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install -r docs/mkdocs/requirements.txt

      - run: |
          mkdocs build -f docs/mkdocs/mkdocs.yml -d ../../site

      - run: |
          tar -cvf artifact.tar -C site/ .

      - uses: actions/upload-artifact@v4
        with:
          name: mkdocs-pages
          path: |
            artifact.tar

  merge:
    needs:
      - build-api
      - build-mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Extract artifacts
        run: |
          mkdir site
          tar -xvf artifacts/api-pages/artifact.tar -C site/
          tar -xvf artifacts/mkdocs-pages/artifact.tar -C site/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - merge
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
